server:
  port: ${SERVER_PORT:9090}

airflow:
  base-url: ${AIRFLOW_BASE_URL:http://airflow-webserver:8080}
  schedule-mode-variable-key: ${AIRFLOW_SCHEDULE_MODE_VARIABLE_KEY:batch_fast_mode}
  username: ${AIRFLOW_USERNAME:admin}
  password: ${AIRFLOW_PASSWORD:admin}
  default-dag-id: ${AIRFLOW_DEFAULT_DAG_ID:ct1_pipeline}
